name: Ferdy Fish Alerts

on:
  schedule:
    - cron: '*/5 * * * *'   # Toutes les 5 minutes
  workflow_dispatch:        # Permet de lancer manuellement

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py

      - name: Commit state
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add last_state.json || true
          git commit -m "Update state" || true
          git push || true
